---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  memberOf: [guests]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guests
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: {$AZ_USERNAME}
  annotations:
    graph.microsoft.com/user-id: ${AZ_USER_ID}
spec:
  profile:
    displayName: ${AZ_USER_NAME}
    email: ${AZ_USER_EMAIL}
  memberOf:
    - ${BACKSTAGE_GROUP} # example 'guests'
